name: Actualizar datos financieros  # Nombre del workflow

on:
  schedule:
    - cron: '0 16 * * *'  # Ejecutar autom치ticamente todos los d칤as a las 16:00 UTC
  workflow_dispatch:       # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  update-stock:
    runs-on: ubuntu-latest  # Define el sistema operativo del entorno de ejecuci칩n (Ubuntu)

    steps:
      - name: Checkout repo  # Paso 1: Clona el repositorio en el runner
        uses: actions/checkout@v3

      - name: Set up Python  # Paso 2: Configura Python en el entorno
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Versi칩n de Python a usar

      - name: Instalar dependencias  # Paso 3: Instala las librer칤as necesarias
        run: |
          pip install yfinance pandas

      - name: Ejecutar script  # Paso 4: Ejecuta tu script Python que descarga y guarda los datos financieros
        run: python Actual_Stock.py

      - name: Commit y push cambios  # Paso 5: Guarda los archivos generados y hace push al repositorio
        uses: EndBug/add-and-commit@v9
        with:
          message: "游늳 Actualizaci칩n autom치tica"  # Mensaje del commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token para autorizar el push al repositorio
